// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: proto/nlp/text_processor.proto

package nlp

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TextProcessor_ProcessText_FullMethodName  = "/nlp.TextProcessor/ProcessText"
	TextProcessor_BatchProcess_FullMethodName = "/nlp.TextProcessor/BatchProcess"
)

// TextProcessorClient is the client API for TextProcessor service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TextProcessorClient interface {
	ProcessText(ctx context.Context, in *ProcessRequest, opts ...grpc.CallOption) (*ProcessResponse, error)
	BatchProcess(ctx context.Context, in *BatchRequest, opts ...grpc.CallOption) (*BatchResponse, error)
}

type textProcessorClient struct {
	cc grpc.ClientConnInterface
}

func NewTextProcessorClient(cc grpc.ClientConnInterface) TextProcessorClient {
	return &textProcessorClient{cc}
}

func (c *textProcessorClient) ProcessText(ctx context.Context, in *ProcessRequest, opts ...grpc.CallOption) (*ProcessResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProcessResponse)
	err := c.cc.Invoke(ctx, TextProcessor_ProcessText_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *textProcessorClient) BatchProcess(ctx context.Context, in *BatchRequest, opts ...grpc.CallOption) (*BatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchResponse)
	err := c.cc.Invoke(ctx, TextProcessor_BatchProcess_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TextProcessorServer is the server API for TextProcessor service.
// All implementations must embed UnimplementedTextProcessorServer
// for forward compatibility.
type TextProcessorServer interface {
	ProcessText(context.Context, *ProcessRequest) (*ProcessResponse, error)
	BatchProcess(context.Context, *BatchRequest) (*BatchResponse, error)
	mustEmbedUnimplementedTextProcessorServer()
}

// UnimplementedTextProcessorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTextProcessorServer struct{}

func (UnimplementedTextProcessorServer) ProcessText(context.Context, *ProcessRequest) (*ProcessResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ProcessText not implemented")
}
func (UnimplementedTextProcessorServer) BatchProcess(context.Context, *BatchRequest) (*BatchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BatchProcess not implemented")
}
func (UnimplementedTextProcessorServer) mustEmbedUnimplementedTextProcessorServer() {}
func (UnimplementedTextProcessorServer) testEmbeddedByValue()                       {}

// UnsafeTextProcessorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TextProcessorServer will
// result in compilation errors.
type UnsafeTextProcessorServer interface {
	mustEmbedUnimplementedTextProcessorServer()
}

func RegisterTextProcessorServer(s grpc.ServiceRegistrar, srv TextProcessorServer) {
	// If the following call panics, it indicates UnimplementedTextProcessorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TextProcessor_ServiceDesc, srv)
}

func _TextProcessor_ProcessText_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProcessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TextProcessorServer).ProcessText(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TextProcessor_ProcessText_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TextProcessorServer).ProcessText(ctx, req.(*ProcessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TextProcessor_BatchProcess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TextProcessorServer).BatchProcess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TextProcessor_BatchProcess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TextProcessorServer).BatchProcess(ctx, req.(*BatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TextProcessor_ServiceDesc is the grpc.ServiceDesc for TextProcessor service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TextProcessor_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nlp.TextProcessor",
	HandlerType: (*TextProcessorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ProcessText",
			Handler:    _TextProcessor_ProcessText_Handler,
		},
		{
			MethodName: "BatchProcess",
			Handler:    _TextProcessor_BatchProcess_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/nlp/text_processor.proto",
}
