// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/nlp/text_processor.proto

package nlp

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProcessRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Task          string                 `protobuf:"bytes,2,opt,name=task,proto3" json:"task,omitempty"` // classify, sentiment, summarize, ner
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessRequest) Reset() {
	*x = ProcessRequest{}
	mi := &file_proto_nlp_text_processor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessRequest) ProtoMessage() {}

func (x *ProcessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_nlp_text_processor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessRequest.ProtoReflect.Descriptor instead.
func (*ProcessRequest) Descriptor() ([]byte, []int) {
	return file_proto_nlp_text_processor_proto_rawDescGZIP(), []int{0}
}

func (x *ProcessRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *ProcessRequest) GetTask() string {
	if x != nil {
		return x.Task
	}
	return ""
}

type ProcessResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        string                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	Confidence    float64                `protobuf:"fixed64,2,opt,name=confidence,proto3" json:"confidence,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessResponse) Reset() {
	*x = ProcessResponse{}
	mi := &file_proto_nlp_text_processor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessResponse) ProtoMessage() {}

func (x *ProcessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_nlp_text_processor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessResponse.ProtoReflect.Descriptor instead.
func (*ProcessResponse) Descriptor() ([]byte, []int) {
	return file_proto_nlp_text_processor_proto_rawDescGZIP(), []int{1}
}

func (x *ProcessResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *ProcessResponse) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *ProcessResponse) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type BatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Texts         []string               `protobuf:"bytes,1,rep,name=texts,proto3" json:"texts,omitempty"`
	Task          string                 `protobuf:"bytes,2,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchRequest) Reset() {
	*x = BatchRequest{}
	mi := &file_proto_nlp_text_processor_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchRequest) ProtoMessage() {}

func (x *BatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_nlp_text_processor_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchRequest.ProtoReflect.Descriptor instead.
func (*BatchRequest) Descriptor() ([]byte, []int) {
	return file_proto_nlp_text_processor_proto_rawDescGZIP(), []int{2}
}

func (x *BatchRequest) GetTexts() []string {
	if x != nil {
		return x.Texts
	}
	return nil
}

func (x *BatchRequest) GetTask() string {
	if x != nil {
		return x.Task
	}
	return ""
}

type BatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*ProcessResponse     `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchResponse) Reset() {
	*x = BatchResponse{}
	mi := &file_proto_nlp_text_processor_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchResponse) ProtoMessage() {}

func (x *BatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_nlp_text_processor_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchResponse.ProtoReflect.Descriptor instead.
func (*BatchResponse) Descriptor() ([]byte, []int) {
	return file_proto_nlp_text_processor_proto_rawDescGZIP(), []int{3}
}

func (x *BatchResponse) GetResults() []*ProcessResponse {
	if x != nil {
		return x.Results
	}
	return nil
}

var File_proto_nlp_text_processor_proto protoreflect.FileDescriptor

const file_proto_nlp_text_processor_proto_rawDesc = "" +
	"\n" +
	"\x1eproto/nlp/text_processor.proto\x12\x03nlp\"8\n" +
	"\x0eProcessRequest\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x12\n" +
	"\x04task\x18\x02 \x01(\tR\x04task\"\xc6\x01\n" +
	"\x0fProcessResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\tR\x06result\x12\x1e\n" +
	"\n" +
	"confidence\x18\x02 \x01(\x01R\n" +
	"confidence\x12>\n" +
	"\bmetadata\x18\x03 \x03(\v2\".nlp.ProcessResponse.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"8\n" +
	"\fBatchRequest\x12\x14\n" +
	"\x05texts\x18\x01 \x03(\tR\x05texts\x12\x12\n" +
	"\x04task\x18\x02 \x01(\tR\x04task\"?\n" +
	"\rBatchResponse\x12.\n" +
	"\aresults\x18\x01 \x03(\v2\x14.nlp.ProcessResponseR\aresults2\x80\x01\n" +
	"\rTextProcessor\x128\n" +
	"\vProcessText\x12\x13.nlp.ProcessRequest\x1a\x14.nlp.ProcessResponse\x125\n" +
	"\fBatchProcess\x12\x11.nlp.BatchRequest\x1a\x12.nlp.BatchResponseB8Z6github.com/NatalieDaw92055/go-nlp-text-pipeline/pb/nlpb\x06proto3"

var (
	file_proto_nlp_text_processor_proto_rawDescOnce sync.Once
	file_proto_nlp_text_processor_proto_rawDescData []byte
)

func file_proto_nlp_text_processor_proto_rawDescGZIP() []byte {
	file_proto_nlp_text_processor_proto_rawDescOnce.Do(func() {
		file_proto_nlp_text_processor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_nlp_text_processor_proto_rawDesc), len(file_proto_nlp_text_processor_proto_rawDesc)))
	})
	return file_proto_nlp_text_processor_proto_rawDescData
}

var file_proto_nlp_text_processor_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_nlp_text_processor_proto_goTypes = []any{
	(*ProcessRequest)(nil),  // 0: nlp.ProcessRequest
	(*ProcessResponse)(nil), // 1: nlp.ProcessResponse
	(*BatchRequest)(nil),    // 2: nlp.BatchRequest
	(*BatchResponse)(nil),   // 3: nlp.BatchResponse
	nil,                     // 4: nlp.ProcessResponse.MetadataEntry
}
var file_proto_nlp_text_processor_proto_depIdxs = []int32{
	4, // 0: nlp.ProcessResponse.metadata:type_name -> nlp.ProcessResponse.MetadataEntry
	1, // 1: nlp.BatchResponse.results:type_name -> nlp.ProcessResponse
	0, // 2: nlp.TextProcessor.ProcessText:input_type -> nlp.ProcessRequest
	2, // 3: nlp.TextProcessor.BatchProcess:input_type -> nlp.BatchRequest
	1, // 4: nlp.TextProcessor.ProcessText:output_type -> nlp.ProcessResponse
	3, // 5: nlp.TextProcessor.BatchProcess:output_type -> nlp.BatchResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_nlp_text_processor_proto_init() }
func file_proto_nlp_text_processor_proto_init() {
	if File_proto_nlp_text_processor_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_nlp_text_processor_proto_rawDesc), len(file_proto_nlp_text_processor_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_nlp_text_processor_proto_goTypes,
		DependencyIndexes: file_proto_nlp_text_processor_proto_depIdxs,
		MessageInfos:      file_proto_nlp_text_processor_proto_msgTypes,
	}.Build()
	File_proto_nlp_text_processor_proto = out.File
	file_proto_nlp_text_processor_proto_goTypes = nil
	file_proto_nlp_text_processor_proto_depIdxs = nil
}
